### ISSUE TITLE
Incorrect method privilage

### ISSUE THREAD

**Issue by taveratch** [PittayutSothanakul/GuessingGame#6]
getSecret() should not be a public method because anyone can access and get the answer from it.
https://github.com/PittayutSothanakul/GuessingGame/blob/master/src/GuessingGame/GuessingGame.java#L103-L105

**Comment by taveratch** [comment]
I think you create getSecret() because you want to return the secret number from play() to the Application. You already have the secret number from the input, why do we need to get the secret number of GuessingGame ?

**Comment by PittayutSothanakul** [comment]
ไม่ได้ใช้แล้วคับผมม
